- name: create ec2 and r53
  hosts: local
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-08135b679290f9e3c # replace with your SG ID
    zone_id: "Z099665035X39GB8IHQAJ" # replace with your ID
    domain_name: "hareesh.space"
    # we can pass instances through command line using -e
    instances: 
    - mongodb
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output

  # - name: print the ec2_output
  #   ansible.builtin.debug:
  #     msg: "{{ ec2_output }}"

  # - name: print public_ip
  #   ansible.builtin.debug: 
  #     msg: "{{ item.instances[0].public_ip_address }}"
  #   loop: "{{ ec2_output.results }}"

  # - name: print private_ip
  #   ansible.builtin.debug: 
  #     msg: "{{ item.instances[0].private_ip_address }}"
  #   loop: "{{ ec2_output.results }}"

  - name: create route53 record
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ item.item }}.{{ domain_name }}" # mongodb.hareesh.space
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      overwrite: true
    loop: "{{ ec2_output.results }}"

    # this is for more instances and records 
    # sudo dnf install ansible -y
    # aws configure
    #     access key & secret key in IAM user under administrater

    # pip3.9 install botocore boto3

    # ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_passwod=DevOps321 01-ec2-r53.yaml
